### ISSUE TITLE
old loki version

### ISSUE THREAD

**Issue by 0xc0decafe** [Raizo62/Loki_on_Kali#1]
Hi,

just to let you know, there is an updated, more recent build of loki, (new features, linked against newer version of libs) can be found here: https://c0decafe.de/loki/nightly/

best

/d

**Comment by Raizo62** [comment]
Hi

Sorry, i didn't see your post before. (??)

Do you speek of "loki_0.3.0-r502-1_amd64.deb", currently ?

**Comment by 0xc0decafe** [comment]
Hi,

yes, the latest build is https://c0decafe.de/loki/nightly/loki_0.3.0-r502-1_amd64.deb

best

**Comment by Raizo62** [comment]
Hi

I have updated Loki_on_Kali with your nightly version loki_0.3.0-r502-1_amd64.deb

But, there are several problems : 
- loki_0.3.0-r502-1_amd64.deb uses python-libpcap, but python-libpcap is not in Kali Linux, nor Debian Sid.
- i have moved the files in /usr/share/pyshared/ to /usr/local/lib/python2.7/dist-packages/, otherwise loki_gtk can't import loki.
- ~~the inject of ospf route (with cisco router) doesn't work. It worked with the last release~~

Edit : The inject of ospf route works :-) Maybe I had a problem with Network-Manager
